<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public.proto

namespace App\Storage\Pilosa\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Attr</code>
 */
class Attr extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Key = 1;</code>
     */
    protected $Key = '';
    /**
     * Generated from protobuf field <code>uint64 Type = 2;</code>
     */
    protected $Type = 0;
    /**
     * Generated from protobuf field <code>string StringValue = 3;</code>
     */
    protected $StringValue = '';
    /**
     * Generated from protobuf field <code>int64 IntValue = 4;</code>
     */
    protected $IntValue = 0;
    /**
     * Generated from protobuf field <code>bool BoolValue = 5;</code>
     */
    protected $BoolValue = false;
    /**
     * Generated from protobuf field <code>double FloatValue = 6;</code>
     */
    protected $FloatValue = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Key
     *     @type int|string $Type
     *     @type string $StringValue
     *     @type int|string $IntValue
     *     @type bool $BoolValue
     *     @type float $FloatValue
     * }
     */
    public function __construct($data = NULL) {
        \App\Storage\Pilosa\Proto\GPBMetadata\PBPublic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->Key;
    }

    /**
     * Generated from protobuf field <code>string Key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->Key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 Type = 2;</code>
     * @return int|string
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>uint64 Type = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkUint64($var);
        $this->Type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string StringValue = 3;</code>
     * @return string
     */
    public function getStringValue()
    {
        return $this->StringValue;
    }

    /**
     * Generated from protobuf field <code>string StringValue = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStringValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->StringValue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 IntValue = 4;</code>
     * @return int|string
     */
    public function getIntValue()
    {
        return $this->IntValue;
    }

    /**
     * Generated from protobuf field <code>int64 IntValue = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIntValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->IntValue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool BoolValue = 5;</code>
     * @return bool
     */
    public function getBoolValue()
    {
        return $this->BoolValue;
    }

    /**
     * Generated from protobuf field <code>bool BoolValue = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolValue($var)
    {
        GPBUtil::checkBool($var);
        $this->BoolValue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double FloatValue = 6;</code>
     * @return float
     */
    public function getFloatValue()
    {
        return $this->FloatValue;
    }

    /**
     * Generated from protobuf field <code>double FloatValue = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setFloatValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->FloatValue = $var;

        return $this;
    }

}

