<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public.proto

namespace App\Storage\Pilosa\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ColumnAttrSet</code>
 */
class ColumnAttrSet extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 ID = 1;</code>
     */
    protected $ID = 0;
    /**
     * Generated from protobuf field <code>string Key = 3;</code>
     */
    protected $Key = '';
    /**
     * Generated from protobuf field <code>repeated .Attr Attrs = 2;</code>
     */
    private $Attrs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $ID
     *     @type string $Key
     *     @type \App\Storage\Pilosa\Proto\Attr[]|\Google\Protobuf\Internal\RepeatedField $Attrs
     * }
     */
    public function __construct($data = NULL) {
        \App\Storage\Pilosa\Proto\GPBMetadata\PBPublic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 ID = 1;</code>
     * @return int|string
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * Generated from protobuf field <code>uint64 ID = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setID($var)
    {
        GPBUtil::checkUint64($var);
        $this->ID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Key = 3;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->Key;
    }

    /**
     * Generated from protobuf field <code>string Key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->Key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Attr Attrs = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttrs()
    {
        return $this->Attrs;
    }

    /**
     * Generated from protobuf field <code>repeated .Attr Attrs = 2;</code>
     * @param \App\Storage\Pilosa\Proto\Attr[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttrs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Storage\Pilosa\Proto\Attr::class);
        $this->Attrs = $arr;

        return $this;
    }

}

