<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public.proto

namespace App\Storage\Pilosa\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ImportRoaringRequest</code>
 */
class ImportRoaringRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool Clear = 1;</code>
     */
    protected $Clear = false;
    /**
     * Generated from protobuf field <code>repeated .ImportRoaringRequestView views = 2;</code>
     */
    private $views;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $Clear
     *     @type \App\Storage\Pilosa\Proto\ImportRoaringRequestView[]|\Google\Protobuf\Internal\RepeatedField $views
     * }
     */
    public function __construct($data = NULL) {
        \App\Storage\Pilosa\Proto\GPBMetadata\PBPublic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool Clear = 1;</code>
     * @return bool
     */
    public function getClear()
    {
        return $this->Clear;
    }

    /**
     * Generated from protobuf field <code>bool Clear = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setClear($var)
    {
        GPBUtil::checkBool($var);
        $this->Clear = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ImportRoaringRequestView views = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getViews()
    {
        return $this->views;
    }

    /**
     * Generated from protobuf field <code>repeated .ImportRoaringRequestView views = 2;</code>
     * @param \App\Storage\Pilosa\Proto\ImportRoaringRequestView[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setViews($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Storage\Pilosa\Proto\ImportRoaringRequestView::class);
        $this->views = $arr;

        return $this;
    }

}

