<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public.proto

namespace App\Storage\Pilosa\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>QueryResult</code>
 */
class QueryResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 Type = 6;</code>
     */
    protected $Type = 0;
    /**
     * Generated from protobuf field <code>.Row Row = 1;</code>
     */
    protected $Row = null;
    /**
     * Generated from protobuf field <code>uint64 N = 2;</code>
     */
    protected $N = 0;
    /**
     * Generated from protobuf field <code>repeated .Pair Pairs = 3;</code>
     */
    private $Pairs;
    /**
     * Generated from protobuf field <code>bool Changed = 4;</code>
     */
    protected $Changed = false;
    /**
     * Generated from protobuf field <code>.ValCount ValCount = 5;</code>
     */
    protected $ValCount = null;
    /**
     * Generated from protobuf field <code>repeated uint64 RowIDs = 7;</code>
     */
    private $RowIDs;
    /**
     * Generated from protobuf field <code>repeated .GroupCount GroupCounts = 8;</code>
     */
    private $GroupCounts;
    /**
     * Generated from protobuf field <code>.RowIdentifiers RowIdentifiers = 9;</code>
     */
    protected $RowIdentifiers = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Type
     *     @type \App\Storage\Pilosa\Proto\Row $Row
     *     @type int|string $N
     *     @type \App\Storage\Pilosa\Proto\Pair[]|\Google\Protobuf\Internal\RepeatedField $Pairs
     *     @type bool $Changed
     *     @type \App\Storage\Pilosa\Proto\ValCount $ValCount
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $RowIDs
     *     @type \App\Storage\Pilosa\Proto\GroupCount[]|\Google\Protobuf\Internal\RepeatedField $GroupCounts
     *     @type \App\Storage\Pilosa\Proto\RowIdentifiers $RowIdentifiers
     * }
     */
    public function __construct($data = NULL) {
        \App\Storage\Pilosa\Proto\GPBMetadata\PBPublic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 Type = 6;</code>
     * @return int
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>uint32 Type = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkUint32($var);
        $this->Type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Row Row = 1;</code>
     * @return \App\Storage\Pilosa\Proto\Row
     */
    public function getRow()
    {
        return isset($this->Row) ? $this->Row : null;
    }

    public function hasRow()
    {
        return isset($this->Row);
    }

    public function clearRow()
    {
        unset($this->Row);
    }

    /**
     * Generated from protobuf field <code>.Row Row = 1;</code>
     * @param \App\Storage\Pilosa\Proto\Row $var
     * @return $this
     */
    public function setRow($var)
    {
        GPBUtil::checkMessage($var, \App\Storage\Pilosa\Proto\Row::class);
        $this->Row = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 N = 2;</code>
     * @return int|string
     */
    public function getN()
    {
        return $this->N;
    }

    /**
     * Generated from protobuf field <code>uint64 N = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setN($var)
    {
        GPBUtil::checkUint64($var);
        $this->N = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Pair Pairs = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPairs()
    {
        return $this->Pairs;
    }

    /**
     * Generated from protobuf field <code>repeated .Pair Pairs = 3;</code>
     * @param \App\Storage\Pilosa\Proto\Pair[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPairs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Storage\Pilosa\Proto\Pair::class);
        $this->Pairs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool Changed = 4;</code>
     * @return bool
     */
    public function getChanged()
    {
        return $this->Changed;
    }

    /**
     * Generated from protobuf field <code>bool Changed = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setChanged($var)
    {
        GPBUtil::checkBool($var);
        $this->Changed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ValCount ValCount = 5;</code>
     * @return \App\Storage\Pilosa\Proto\ValCount
     */
    public function getValCount()
    {
        return isset($this->ValCount) ? $this->ValCount : null;
    }

    public function hasValCount()
    {
        return isset($this->ValCount);
    }

    public function clearValCount()
    {
        unset($this->ValCount);
    }

    /**
     * Generated from protobuf field <code>.ValCount ValCount = 5;</code>
     * @param \App\Storage\Pilosa\Proto\ValCount $var
     * @return $this
     */
    public function setValCount($var)
    {
        GPBUtil::checkMessage($var, \App\Storage\Pilosa\Proto\ValCount::class);
        $this->ValCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 RowIDs = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRowIDs()
    {
        return $this->RowIDs;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 RowIDs = 7;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRowIDs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->RowIDs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .GroupCount GroupCounts = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGroupCounts()
    {
        return $this->GroupCounts;
    }

    /**
     * Generated from protobuf field <code>repeated .GroupCount GroupCounts = 8;</code>
     * @param \App\Storage\Pilosa\Proto\GroupCount[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGroupCounts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Storage\Pilosa\Proto\GroupCount::class);
        $this->GroupCounts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.RowIdentifiers RowIdentifiers = 9;</code>
     * @return \App\Storage\Pilosa\Proto\RowIdentifiers
     */
    public function getRowIdentifiers()
    {
        return isset($this->RowIdentifiers) ? $this->RowIdentifiers : null;
    }

    public function hasRowIdentifiers()
    {
        return isset($this->RowIdentifiers);
    }

    public function clearRowIdentifiers()
    {
        unset($this->RowIdentifiers);
    }

    /**
     * Generated from protobuf field <code>.RowIdentifiers RowIdentifiers = 9;</code>
     * @param \App\Storage\Pilosa\Proto\RowIdentifiers $var
     * @return $this
     */
    public function setRowIdentifiers($var)
    {
        GPBUtil::checkMessage($var, \App\Storage\Pilosa\Proto\RowIdentifiers::class);
        $this->RowIdentifiers = $var;

        return $this;
    }

}

