<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public.proto

namespace App\Storage\Pilosa\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>QueryRequest</code>
 */
class QueryRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Query = 1;</code>
     */
    protected $Query = '';
    /**
     * Generated from protobuf field <code>repeated uint64 Shards = 2;</code>
     */
    private $Shards;
    /**
     * Generated from protobuf field <code>bool ColumnAttrs = 3;</code>
     */
    protected $ColumnAttrs = false;
    /**
     * Generated from protobuf field <code>bool Remote = 5;</code>
     */
    protected $Remote = false;
    /**
     * Generated from protobuf field <code>bool ExcludeRowAttrs = 6;</code>
     */
    protected $ExcludeRowAttrs = false;
    /**
     * Generated from protobuf field <code>bool ExcludeColumns = 7;</code>
     */
    protected $ExcludeColumns = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Query
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $Shards
     *     @type bool $ColumnAttrs
     *     @type bool $Remote
     *     @type bool $ExcludeRowAttrs
     *     @type bool $ExcludeColumns
     * }
     */
    public function __construct($data = NULL) {
        \App\Storage\Pilosa\Proto\GPBMetadata\PBPublic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Query = 1;</code>
     * @return string
     */
    public function getQuery()
    {
        return $this->Query;
    }

    /**
     * Generated from protobuf field <code>string Query = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setQuery($var)
    {
        GPBUtil::checkString($var, True);
        $this->Query = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 Shards = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getShards()
    {
        return $this->Shards;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 Shards = 2;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setShards($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->Shards = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool ColumnAttrs = 3;</code>
     * @return bool
     */
    public function getColumnAttrs()
    {
        return $this->ColumnAttrs;
    }

    /**
     * Generated from protobuf field <code>bool ColumnAttrs = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setColumnAttrs($var)
    {
        GPBUtil::checkBool($var);
        $this->ColumnAttrs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool Remote = 5;</code>
     * @return bool
     */
    public function getRemote()
    {
        return $this->Remote;
    }

    /**
     * Generated from protobuf field <code>bool Remote = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setRemote($var)
    {
        GPBUtil::checkBool($var);
        $this->Remote = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool ExcludeRowAttrs = 6;</code>
     * @return bool
     */
    public function getExcludeRowAttrs()
    {
        return $this->ExcludeRowAttrs;
    }

    /**
     * Generated from protobuf field <code>bool ExcludeRowAttrs = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setExcludeRowAttrs($var)
    {
        GPBUtil::checkBool($var);
        $this->ExcludeRowAttrs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool ExcludeColumns = 7;</code>
     * @return bool
     */
    public function getExcludeColumns()
    {
        return $this->ExcludeColumns;
    }

    /**
     * Generated from protobuf field <code>bool ExcludeColumns = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setExcludeColumns($var)
    {
        GPBUtil::checkBool($var);
        $this->ExcludeColumns = $var;

        return $this;
    }

}

