<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public.proto

namespace App\Storage\Pilosa\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>QueryResponse</code>
 */
class QueryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Err = 1;</code>
     */
    protected $Err = '';
    /**
     * Generated from protobuf field <code>repeated .QueryResult Results = 2;</code>
     */
    private $Results;
    /**
     * Generated from protobuf field <code>repeated .ColumnAttrSet ColumnAttrSets = 3;</code>
     */
    private $ColumnAttrSets;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Err
     *     @type \App\Storage\Pilosa\Proto\QueryResult[]|\Google\Protobuf\Internal\RepeatedField $Results
     *     @type \App\Storage\Pilosa\Proto\ColumnAttrSet[]|\Google\Protobuf\Internal\RepeatedField $ColumnAttrSets
     * }
     */
    public function __construct($data = NULL) {
        \App\Storage\Pilosa\Proto\GPBMetadata\PBPublic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Err = 1;</code>
     * @return string
     */
    public function getErr()
    {
        return $this->Err;
    }

    /**
     * Generated from protobuf field <code>string Err = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setErr($var)
    {
        GPBUtil::checkString($var, True);
        $this->Err = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .QueryResult Results = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResults()
    {
        return $this->Results;
    }

    /**
     * Generated from protobuf field <code>repeated .QueryResult Results = 2;</code>
     * @param \App\Storage\Pilosa\Proto\QueryResult[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Storage\Pilosa\Proto\QueryResult::class);
        $this->Results = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ColumnAttrSet ColumnAttrSets = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getColumnAttrSets()
    {
        return $this->ColumnAttrSets;
    }

    /**
     * Generated from protobuf field <code>repeated .ColumnAttrSet ColumnAttrSets = 3;</code>
     * @param \App\Storage\Pilosa\Proto\ColumnAttrSet[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setColumnAttrSets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Storage\Pilosa\Proto\ColumnAttrSet::class);
        $this->ColumnAttrSets = $arr;

        return $this;
    }

}

