<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public.proto

namespace App\Storage\Pilosa\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TranslateKeysRequest</code>
 */
class TranslateKeysRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Index = 1;</code>
     */
    protected $Index = '';
    /**
     * Generated from protobuf field <code>string Field = 2;</code>
     */
    protected $Field = '';
    /**
     * Generated from protobuf field <code>repeated string Keys = 3;</code>
     */
    private $Keys;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Index
     *     @type string $Field
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Keys
     * }
     */
    public function __construct($data = NULL) {
        \App\Storage\Pilosa\Proto\GPBMetadata\PBPublic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Index = 1;</code>
     * @return string
     */
    public function getIndex()
    {
        return $this->Index;
    }

    /**
     * Generated from protobuf field <code>string Index = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkString($var, True);
        $this->Index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Field = 2;</code>
     * @return string
     */
    public function getField()
    {
        return $this->Field;
    }

    /**
     * Generated from protobuf field <code>string Field = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setField($var)
    {
        GPBUtil::checkString($var, True);
        $this->Field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string Keys = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeys()
    {
        return $this->Keys;
    }

    /**
     * Generated from protobuf field <code>repeated string Keys = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Keys = $arr;

        return $this;
    }

}

