<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public.proto

namespace App\Storage\Pilosa\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ValCount</code>
 */
class ValCount extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 Val = 1;</code>
     */
    protected $Val = 0;
    /**
     * Generated from protobuf field <code>int64 Count = 2;</code>
     */
    protected $Count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $Val
     *     @type int|string $Count
     * }
     */
    public function __construct($data = NULL) {
        \App\Storage\Pilosa\Proto\GPBMetadata\PBPublic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 Val = 1;</code>
     * @return int|string
     */
    public function getVal()
    {
        return $this->Val;
    }

    /**
     * Generated from protobuf field <code>int64 Val = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVal($var)
    {
        GPBUtil::checkInt64($var);
        $this->Val = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Count = 2;</code>
     * @return int|string
     */
    public function getCount()
    {
        return $this->Count;
    }

    /**
     * Generated from protobuf field <code>int64 Count = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->Count = $var;

        return $this;
    }

}

