<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public.proto

namespace App\Storage\Pilosa\Proto\GPBMetadata;

class PBPublic
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
­
public.proto":
Row
Columns (
Keys (	
Attrs (2.Attr",
RowIdentifiers
Rows (
Keys (	".
Pair

ID (
Key (	
Count ("8
FieldRow
Field (	
RowID (
RowKey (	"5

GroupCount
Group (2	.FieldRow
Count ("&
ValCount
Val (
Count (">
ColumnAttrSet

ID (
Key (	
Attrs (2.Attr"o
Attr
Key (	
Type (
StringValue (	
IntValue (
	BoolValue (

FloatValue ("
AttrMap
Attrs (2.Attr"ƒ
QueryRequest
Query (	
Shards (
ColumnAttrs (
Remote (
ExcludeRowAttrs (
ExcludeColumns ("c
QueryResponse
Err (	
Results (2.QueryResult&
ColumnAttrSets (2.ColumnAttrSet"Ø
QueryResult
Type (
Row (2.Row	
N (
Pairs (2.Pair
Changed (
ValCount (2	.ValCount
RowIDs ( 
GroupCounts (2.GroupCount\'
RowIdentifiers	 (2.RowIdentifiers"˜
ImportRequest
Index (	
Field (	
Shard (
RowIDs (
	ColumnIDs (
RowKeys (	

ColumnKeys (	

Timestamps ("x
ImportValueRequest
Index (	
Field (	
Shard (
	ColumnIDs (

ColumnKeys (	
Values ("B
TranslateKeysRequest
Index (	
Field (	
Keys (	"$
TranslateKeysResponse
IDs ("6
ImportRoaringRequestView
Name (	
Data ("O
ImportRoaringRequest
Clear ((
views (2.ImportRoaringRequestViewBBÊApp\\Storage\\Pilosa\\Protoâ$App\\Storage\\Pilosa\\Proto\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

